#!/bin/bash
#
# Licensed Materials - Property of IBM
# 5655-OD1
# COPYRIGHT IBM CORP. 2017
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with
# IBM Corp.
#
# toEBCDIC - Convert file(s) from ASCII to EBCDIC
#

getPerms ()
{
  convert_to_num ()
  {
    TOP=0
    MID=0
    BOT=0
    if [[ ${1:0:1} == "r" ]] ; then
      TOP=4
    fi
    if [[ ${1:1:1} == "w" ]] ; then
      MID=2
    fi
    if [[ ${1:2:1} == "x" ]] ; then
      BOT=1
    fi
    RESULT=$((TOP + MID + BOT))
  }
  
  # should have used find, need to figure out how the uss find is different
  PERMS=$(ls -l "$1" | awk '{print $1}')
  USER_PERMS=${PERMS:1:3}
  GROUP_PERMS=${PERMS:4:3}
  OWNER_PERMS=${PERMS:7:3}

  convert_to_num "$USER_PERMS"
  USER_NUM=$RESULT
  convert_to_num "$GROUP_PERMS"
  GROUP_NUM=$RESULT
  convert_to_num "$OWNER_PERMS"
  OWNER_NUM=$RESULT

  perms="0$USER_NUM$GROUP_NUM$OWNER_NUM"
}

FORCE=false


until [ "$#" -eq 0 ]; do
  if [[ "$1" == "-f" ]]; then
    FORCE=true
    shift
  fi
  if [ -d "$1" ]; then
    for file in "$1"/*; do
      if ! /bin/test "$file" -CS IBM-1047 || [ "$FORCE" == "true" ]; then
        iconv -f ISO8859-1 -t IBM-1047 "$file" >> "$file".toEBCDICtmp
        getPerms "$file"
        rm "$file"
        mv "$file".toEBCDICtmp "$file"
        chmod $perms "$file"
        chtag -t -c IBM-1047 "$file"
      else
        echo "$file is already tagged EBCDIC"
      fi
    done
  else
    if [ -f "$1" ]; then
      if /bin/test "$1" -CS IBM-1047 || [ "$FORCE" == "true" ]; then
        iconv -f ISO8859-1 -t IBM-1047 "$1" > "$1".toEBCDICtmp
        getPerms "$1"
        rm "$1"
        mv "$1".toEBCDICtmp "$1"
        chmod $perms "$1"
        chtag -t -c IBM-1047 "$1"
      else
        echo "$1 is already tagged EBCDIC"
      fi
    else
      echo "$1 is not valid"
    fi
  fi
  shift
done

exit 0
